web:
  host: "0.0.0.0"
  port: 8293

ws:
  host: "0.0.0.0"
  port: 38562

secret: 'YOUR_SECRET'

# If your websocket is proxied to lies under the same domain, uncomment the following line and specify the prefix, without tailing slash
# proxied: '/websocket'
